Develop
kasper93721/CV pull request #2
Opened 2022-10-02 13:23 UTC by kasper93721

2022-10-02 19:55 UTC, a1exalexander requested changes
Не вистачає ще лінка на github pages, щоб можна було переглянути, як виглядає сайт. Лінк можна додати в спеціальне поле на головній сторінці репозиторія, в налаштуваннях

2022-10-02 19:57 UTC, a1exalexander commented
Також можна видалити перші теги `div`, які обертають `h1` та `h2` теги, відповідно, оскільки ці теои і так являються блоковими тегами

2022-10-02 19:58 UTC, kasper93721 commented
Окей, виправлю

нд, 2 жовт. 2022 р. о 22:57 Alexander Ratushnyi ***@***.***>
пише:

> Також можна видалити перші теги div, які обертають h1 та h2 теги,
> відповідно, оскільки ці теои і так являються блоковими тегами
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kasper93721/CV/pull/2#issuecomment-1264720712>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3GQSMQP4LZRFGNHJUSWOIDWBHSLHANCNFSM6AAAAAAQ2445TU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-03 13:12 UTC, a1exalexander approved these changes

2022-10-03 13:12 UTC, a1exalexander commented on index.html
> +   <div><h2>Job Title</h2></div>
```suggestion
   <h1>Valera Mykytenko</h1>
   <h2>Job Title</h2>
```
Ось ці теги видалити, я мав на увазі)

2022-10-03 13:13 UTC, merged